### ISSUE TITLE
Library file mk_quaternion.zsc throws errors

### ISSUE THREAD

**Issue by vanessakindell** [Studio-Baguette-3/retrotokyo#2]
Library file mk_quaternion.zsc throws the following errors when trying to load up the TC in the current version of GZDoom.*

`Attempt to get invalid state Death from actor RT_ThermopticCamoFlash.
10 warnings while compiling retrotokyo.ipk3:zscript.txt
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 37:
Unknown function Create
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 40:
Unknown function Create
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 45:
Unknown function create_axis
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 46:
Unknown function create_axis
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 47:
Unknown function create_axis
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 48:
Unknown identifier 'zrot'
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 49:
Unknown identifier 'Sum'
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 50:
Unknown identifier 'Sum'
Script error, "retrotokyo.ipk3:zscript/lib/mk_quaternion.zsc" line 94:
Unknown function Create`

* GZDoom g4.11.3 - 2023-10-26 15:18:50 -0400 - SDL version

**Comment by vanessakindell** [comment]
The fix is simple: remove mk_quaternion.zsc and remove line 5 in zscript.txt.
Quaternion is now an existing class in GZDoom so it is no longer needed.

**Comment by jorisvddonk** [comment]
Splendid! Thanks for the report and the mention of the fix; I wasn't aware Quaternion is now available natively.
